<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net11.0</TargetFramework>
        <GenerateProgramFile>false</GenerateProgramFile>
        <DefineConstants>$(DefineConstants);TEST_NET6_0_OR_GREATER</DefineConstants>
        <RuntimeAsyncBitsPath Condition="'$(RuntimeAsyncBitsPath)' == ''">d:\source\fsharp\artifacts\bin</RuntimeAsyncBitsPath>
        <DotnetFscCompilerPath>$(RuntimeAsyncBitsPath)\fsc\Release\net11.0\fsc.dll</DotnetFscCompilerPath>
        <DisableImplicitFSharpCoreReference>True</DisableImplicitFSharpCoreReference>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../src/IcedTasks.11/IcedTasks.11.fsproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="FSharp.Core" VersionOverride="7.0.400" ExcludeAssets="all" PrivateAssets="all" />
        <Reference Include="FSharp.Core">
            <HintPath>$(RuntimeAsyncBitsPath)\FSharp.Core\Release\net10.0\FSharp.Core.dll</HintPath>
        </Reference>
    </ItemGroup>
    <ItemGroup>
        <Compile Include="Expect.fs" />
        <Compile Include="AsyncExTests.fs" />
        <Compile Include="TaskTests.fs" />
        <Compile Include="TaskBackgroundTests.fs" />
        <Compile Include="ValueTaskTests.fs" />
        <Compile Include="PoolingValueTaskTests.fs" />
        <Compile Include="CancellableTaskTests.fs" />
        <Compile Include="CancellableValueTaskTests.fs" />
        <Compile Include="CancellablePoolingValueTaskTests.fs" />
        <Compile Include="ColdTaskTests.fs" />
        <Compile Include="ParallelAsyncTests.fs" />
        <Compile Include="Main.fs" />
    </ItemGroup>

</Project>
